### ISSUE TITLE
GitHub organizations don't show

### ISSUE THREAD

**Issue by ghost** [MeteorPackaging/autopublish.meteor.com#12]
Hi,

my GitHub organizations don't show on http://autopublish.meteor.com/accounts.

![bildschirmfoto 2015-04-03 um 14 44 19](https://cloud.githubusercontent.com/assets/727955/6982282/f9e80d68-da0f-11e4-8013-2cd983557187.png)

**Comment by splendido** [comment]
See #9
I guess it's the same scenario...

Let me know!

**Comment by ghost** [comment]
It turned out to be the same issue. I never knew about this option. It's on the page `https://github.com/orgs/<REPOSITORY>/people`
