### ISSUE TITLE
Cannot choose a repository where the package is in a subfolder

### ISSUE THREAD

**Issue by ghost** [MeteorPackaging/autopublish.meteor.com#14]
For velocity:core the package is under src/. https://github.com/meteor-velocity/velocity. This is necessary because we have test-app for testing in the same repository.

**Comment by splendido** [comment]
that's a big problem...
you'd need to be able to navigate your repository to select the folder where the package resides and to specify that folder as the cwd for `meteor publish`.
Actually I see this a little time consuming to be implemented... :(

what if you put things the other way around?
package in the root folder and `test-app` as a regular (unusued, for the package) subfolder?
;-)

**Comment by splendido** [comment]
...out of curiosity, are you trynig to publish official Velocity releases with autopublish?
That would be great! :-)

**Comment by ghost** [comment]
> ...out of curiosity, are you trynig to publish official Velocity releases with autopublish?

Yes

> package in the root folder and test-app as a regular (unusued, for the package) subfolder?

we had that before. Maybe we can go back to that.

**Comment by splendido** [comment]
ok, good!
