### ISSUE TITLE
Cannot login to autopublish.meteor.com

### ISSUE THREAD

**Issue by zachariahtimothy** [MeteorPackaging/autopublish.meteor.com#18]
When I click the Login with Github button on this site I get the Github challenge window then after entering credentials the window goes away and nothing else happens. I am not logged in. Have tried this in Chrome and Safari, as well as in incognito mode.

**Comment by splendido** [comment]
Are you by chance on `https`?
See #15 and #16

**Comment by zachariahtimothy** [comment]
Yep, that must be it. I noticed the oauth callback url was not https. I
switched to http and now the login works. Thanks!

---

Zach Curtis
P: 970.590.6383
E: zachariahtimothy@gmail.com
T: @zachariahCurtis https://twitter.com/#!/@zachariahCurtis
B: http://zachariahtimothy.wordpress.com/

**Comment by splendido** [comment]
We'll have to sort this out quickly...

Thanks for reporting
