### ISSUE TITLE
Publishing stuck at "Connected to support machine"

### ISSUE THREAD

**Issue by zimme** [MeteorPackaging/autopublish.meteor.com#23]
I have no idea what's happening, but my publish operations are stuck at this state.

You should be able to see it if you browse into the landing page of autopublish

**Comment by splendido** [comment]
wow, that's against any real usecase...
The only thing I can try to do is deploying again to get the server restarted...

**Comment by zimme** [comment]
I've manually published my packages for this version... but this was a weird error, maybe we need a timeout in some places to prevent this kind of hold-up

**Comment by zimme** [comment]
Closing this as we have no reason to believe it's going to happen again, we'll just reopen if it does.
