### ISSUE TITLE
Site down times

### ISSUE THREAD

**Issue by splendido** [MeteorPackaging/autopublish.meteor.com#3]
As we all know, deploys on meteor.com are intended for easiness of testing production apps but not really to be used for real production apps.
This is why any deployment performed by common meteor users might be pushed down after a certain period of time without traffic.

How we go around this @dandv, @raix?

...I'm ready to _launch_ this brand new service by asking Jack from Semantic-UI to jump on board, but I suspect we might miss some hook trigger from GitHub in case the payload arrives and autopublish.meteor.com is down :(

Should we ping someone from MDG right now?

...at a first time I wanted to have some actual working recurrent publishing (semantic, bootstrap, fontawesome, might be a great triplet ;-) ) before asking for official resources (access to always available build machines and a _regular_ 3rd level domain without down times)

Thoughts?

**Comment by splendido** [comment]
Is there any chance MDG will support this by ensuring there will be no down times?
@avital, @debergalis, @dgreensp, @glasser, @gschmidt, @ekatek, @estark37
Sorry to cc you guys...

Lets have a look at the video on [this page](http://autopublish.meteor.com/howitworks) if you get a chance, to grasp what's going on here.

Thanks,
Luca

**Comment by debergalis** [comment]
Ask and ye shall receive.  We've set autopublish to never sleep.

**Comment by splendido** [comment]
...already done? Really?!?!

Awesome, tnx! :)

**Comment by debergalis** [comment]
np

**Comment by splendido** [comment]
Brilliant,
tnx again!

**Comment by raix** [comment]
:+1:

**Comment by splendido** [comment]
_That's one small step for the project, one giant leap for the Meteor community_

**Comment by raix** [comment]
@splendido Its cool, I'm pretty booked at the moment so I havent tested anything yet, but I'll join in later to help with the meteorsession stuff unless you or others get there first - perhaps merge other stuff from the mbr tool like changelog generator etc. if relevant

**Comment by splendido** [comment]
You're very welcome!
...no need to say it ;-)

**Comment by dandv** [comment]
:+1:

**Comment by paralin** [comment]
Awesome! good work. I was going to suggest we could run a DigitalOcean node.
