### ISSUE TITLE
Improve texts

### ISSUE THREAD

**Issue by splendido** [MeteorPackaging/autopublish.meteor.com#4]
...better done by someone speaking English better than me ;-)

If you don't want to care about UI stuff, just drop some text and then we'll try to somehow flow it into the UI.

**Comment by dandv** [comment]
I've just proofread https://github.com/MeteorPackaging/autopublish.meteor.com/wiki again - looks good. Let me look at the other docs too.

**Comment by dandv** [comment]
Proofread the [Caveat page](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/Caveat).

Question: can we avoid replacing the version number, at least in package.js, but reading it directly from the main file that contains the version number? (e.g. package.json). I've [done this before](https://github.com/dandv/meteor-webix/blob/master/package.js#L6) and the only corner case is when the package isn't tested from its root directory, in which case `package.js` can't find the directory it's in (something surprisingly hard to do in Meteor, or even impossible - [1](stackoverflow.com/questions/27435797/how-do-i-obtain-the-path-of-a-file-in-a-meteor-package), [2](http://stackoverflow.com/questions/16721351/how-to-get-the-current-directory-within-a-meteor-smart-package), [3](http://stackoverflow.com/questions/26497027/how-to-get-the-current-directory-of-a-package-file)).

**Comment by dandv** [comment]
Proofread the [hooks page](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/How-to-manually-set-up-web-hooks).

This concludes proofreading, I believe.

**Comment by splendido** [comment]
Thanks for having a look at this!

What about the texts appearing on the website?
I'm not native English (you neither actaully, but I guess you're more proficient than me in English...) so there might be some weird sentence construction

e.g. the headline was "The portal to Automated Package Publication!" but yesterday i changed it to "The portal to Automated Package Publishing!", not sure which is the correct one..

**Comment by splendido** [comment]
The thing about having the `package.js` loading the `package.json` to figure out the version numer is exactly as you said: it prevents the possibility to use the package as a local package (be it directly cloned under your app's `packages` folder or simlinked to it.

**This basically prevent any debug attempt while using the package locally from within a test application!**
The only possibility would be to have extensive test with full coverage...

**Comment by dandv** [comment]
> What about the texts appearing on the website?

I've been through those too (see the last commit). Maybe I should've created a PR. App needs a new deploy anyway.

> This basically prevent any debug attempt while using the package locally from within a test application!

For debugging, I've just set the version to a hardcoded string in case the package.json file isn't found:

https://github.com/dandv/meteor-webix/blob/master/package.js#L4-L10

**Comment by splendido** [comment]
I see, this can be a good workaround!

Going do deploy latest websire version now...
