### ISSUE TITLE
Use Meteor build machines

### ISSUE THREAD

**Issue by splendido** [MeteorPackaging/autopublish.meteor.com#6]
We've got green light to use (not to abuse!) `meteor admin get-machine` for packages publishing!
See [here](https://github.com/meteor/meteor/issues/2569#issuecomment-71940905).

So the sequence of command need to be updated to request the VM and also to `meteor login` the packaging user.

**Comment by dandv** [comment]
:100: !

**Comment by splendido** [comment]
See 5ee8658fe71190be6d0bebc98769371f35b3bb38
