### ISSUE TITLE
Organization not listed

### ISSUE THREAD

**Issue by lorensr** [MeteorPackaging/autopublish.meteor.com#9]
![image](https://cloud.githubusercontent.com/assets/251288/6409217/2426bad2-be15-11e4-94fa-06d21cf23f68.png)

I'm trying to use this with

https://github.com/parlaywithme/coinbase

The org has some private repos, but this one is public.

**Comment by splendido** [comment]
From what I can see on [your profile page](https://github.com/lorensr) the organizations listed match.
And `parlaywithme` has no [public members](https://github.com/orgs/parlaywithme/people).

Have you checked whether `coinbase` is listed under your repositories (clicking on your username)?

...otherwise I guess we should put `read:orgs` [scope](https://developer.github.com/v3/oauth/#scopes) back in. This should gran read access to organizations

**Comment by lorensr** [comment]
Thanks, I was unaware of this setting:
![image](https://cloud.githubusercontent.com/assets/251288/6409790/d17114ba-be1c-11e4-99ba-55e9cec93e83.png)
on my org settings page. I made myself public, and now see it in your UI.

**Comment by splendido** [comment]
:+1:

**Comment by splendido** [comment]
may I ask how are you going to use autopublish?
for your own releases? or are you going to ping the original maintainers?

**Comment by lorensr** [comment]
for releasing parlay:coinbase, which I am the maintainer of.

would be cool if you monitored my npm dependencies and auto edited my
package.js to use the new versions and the published (what i originally
thought you did after seeing the devshop presentation :)

**Comment by splendido** [comment]
Well, there's a bit of work to do actually...
Have you read the [wiki](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki)?

The idea is to ask the 3rd party library maintainers to accept a PR to integrate the `package.js` file directly on the upstream repo.
See [known integrations](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/Known-Attempts-to-get-Official-Integration) and have a look at those PR.

...this said, we're working on a different workflow (which is not yet ready) which requires only the weebhook from the upstream repo: but I guess this won't ensure the npm package is already updated when the trigger reaches autopublish.meteor.com.
